default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: demo
  password: 1234
  host: localhost

development:
  <<: *default
  database: school_management_development

test:
  <<: *default
  database: school_management_test

production:
  <<: *default
  database: school_management_production
  username: your_production_username
  password: <%= ENV['SCHOOL_MANAGEMENT_DATABASE_PASSWORD'] %>
